language: python
cache:
  - pip

matrix:
  include:
    - name: linux-python3.6
      os: linux
      python: 3.6
    - name: linux-python3.7
      os: linux
      python: 3.7
    - name: linux-python3.8
      os: linux
      python: 3.8
    - name: osx-python3.6-conda
      os: osx
      language: generic
      env:
      - TRAVIS_PYTHON_VERSION=3.6
      - OSX_PKG_ENV=miniconda
    - name: osx-python3.7-brew
      os: osx
      language: generic
      env:
      - TRAVIS_PYTHON_VERSION=3.7
      - OSX_PKG_ENV=brew
      cache:
        # As for now travis caches only "$HOME/.cache/pip"
        # https://docs.travis-ci.com/user/caching/#pip-cache
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          - $HOME/Library/Caches/Homebrew
      addons:
        homebrew:
          packages:
            - libomp
          update: true
    - name: osx-python3.8-brew
      os: osx
      language: generic
      env:
      - TRAVIS_PYTHON_VERSION=3.8
      - OSX_PKG_ENV=brew
      cache:
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          - $TRAVIS_BUILD_DIR/target
          # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew/
          # used in OSX custom build script dealing with local bottle caching
          - $HOME/local_bottle_metadata
      addons:
        homebrew:
          packages:
            - libomp
          update: true
      before_install: |
        if [ -n "$IS_OSX" ]; then
            TAPS="$(brew --repository)/Library/Taps"
            if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
                rm -rf "$TAPS/caskroom/homebrew-cask"
            fi
            find "$TAPS" -type d -name .git -exec \
                    bash -xec '
                        cd $(dirname '\''{}'\'') || echo "status: $?"
                        git clean -fxd || echo "status: $?"
                        sleep 1 || echo "status: $?"
                        git status || echo "status: $?"' \; || echo "status: $?"
            brew_cache_cleanup
        fi
      before_cache: |
        # Cleanup dirs to be cached
        set -e; set -x
        if [ -n "$IS_OSX" ]; then
            # When Taps is cached, this dir causes "Error: file exists" on `brew update`
            if [ -e "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask" ]; then
                rm -rf "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask"
            fi
            brew_cache_cleanup
        fi
        set +x; set +e

#    - os: windows
#      language: shell
#      before_install:
#      - choco install python3 --version 3.7.4
#      - python --version
#      - python -m pip install --upgrade pip
#      - pip3 install --upgrade pytest
#      - pip3 install codecov
#      - pip3 install cython
#      - pip3 install numpy
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      source .travis/osx_install.sh;
    else
      source .travis/linux_install.sh;
    fi
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov


install:
  - if [[ "${OSX_PKG_ENV}" == miniconda ]]; then
      conda config --add channels conda-forge;
      conda install ipython;
      conda install --file requirements.txt;
    elif [[ "${OSX_PKG_ENV}" == brew ]]; then
      pip install cython;
      pip install numpy;
    fi
  - pip install .

script:
  - pytest # run tests
after_success:
  - codecov # submit coverage

notifications:
  email: false